"""Registry of warcraftlogs CLI commands for payload envelope documentation and tests."""

from __future__ import annotations

ALL_COMMANDS: tuple[str, ...] = (
    "search",
    "resolve",
    "doctor",
    "rate-limit",
    "regions",
    "expansions",
    "server",
    "zones",
    "zone",
    "encounter",
    "encounter-rankings",
    "guild",
    "guild-rankings",
    "guild-members",
    "guild-attendance",
    "character",
    "character-rankings",
    "report",
    "reports",
    "guild-reports",
    "boss-kills",
    "top-kills",
    "spec-kill-samples",
    "boss-spec-usage",
    "ability-usage-summary",
    "comp-samples",
    "report-encounter",
    "report-encounter-players",
    "report-player-talents",
    "report-encounter-casts",
    "report-encounter-buffs",
    "report-encounter-aura-summary",
    "report-encounter-aura-compare",
    "report-encounter-damage-source-summary",
    "report-encounter-damage-target-summary",
    "report-encounter-damage-breakdown",
    "kill-time-distribution",
    "report-fights",
    "graphql",
    "report-events",
    "report-table",
    "report-graph",
    "report-master-data",
    "report-player-details",
    "report-rankings",
)
