#!/usr/bin/env python3
"""Generate docs/reference/<console-script>.md from the Typer apps themselves.

The reference is the only place flag lists live: prose docs describe workflows and link here.
`make reference` rewrites the files; tests/test_command_reference.py fails when they are stale.
"""

from __future__ import annotations

import argparse
import importlib
import sys
import tomllib
from pathlib import Path

import typer
from click import Argument, Command, Option, Parameter

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_DIR = REPO_ROOT / "docs" / "reference"
GENERATED_HEADER = (
    "<!-- Generated by scripts/generate_command_reference.py. Do not edit by hand; run `make reference`. -->"
)

for _src in sorted(REPO_ROOT.glob("packages/*/src")):
    if str(_src) not in sys.path:
        sys.path.insert(0, str(_src))


def console_scripts() -> dict[str, str]:
    with (REPO_ROOT / "pyproject.toml").open("rb") as handle:
        scripts: dict[str, str] = tomllib.load(handle)["project"]["scripts"]
    return scripts


def _load_group(entry_point: str) -> Command:
    module_name = entry_point.split(":", 1)[0]
    module = importlib.import_module(module_name)
    return typer.main.get_command(module.app)


# Typer >= 0.27 wraps commands in its own click shim classes, so `isinstance(x, click.Group)` is
# False for a real Typer app. Everything below duck-types against the click parameter protocol.
def _is_group(command: Command) -> bool:
    return hasattr(command, "commands")


def _cell(text: str | None) -> str:
    if not text:
        return ""
    return " ".join(text.split()).replace("|", "\\|")


def _type_label(param: Parameter) -> str:
    param_type = param.type
    choices = getattr(param_type, "choices", None)
    if choices:
        return _cell("choice: " + ", ".join(str(choice) for choice in choices))
    if getattr(param, "multiple", False):
        return _cell(f"{param_type.name} (repeatable)")
    return _cell(param_type.name)


def _default_label(param: Parameter) -> str:
    if param.required:
        return "required"
    default = param.default
    if default is None:
        return ""
    if isinstance(default, bool):
        return "true" if default else "false"
    if isinstance(default, (list, tuple)):
        return _cell(", ".join(str(item) for item in default)) if default else ""
    return _cell(str(default))


def _flag_label(param: Option) -> str:
    return _cell(" / ".join([*param.opts, *param.secondary_opts]))


def _option_table(params: list[Option]) -> list[str]:
    lines = ["| Option | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for param in params:
        lines.append(f"| `{_flag_label(param)}` | {_type_label(param)} | {_default_label(param)} | {_cell(param.help)} |")
    return lines


def _argument_table(params: list[Argument]) -> list[str]:
    lines = ["| Argument | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for param in params:
        help_text = _cell(getattr(param, "help", None))
        lines.append(f"| `{param.name}` | {_type_label(param)} | {_default_label(param)} | {help_text} |")
    return lines


def _split_params(command: Command) -> tuple[list[Argument], list[Option]]:
    arguments: list[Argument] = []
    options: list[Option] = []
    for param in command.params:
        if param.param_type_name == "argument":
            arguments.append(param)
        elif param.name != "help":
            options.append(param)
    return arguments, options


def _subcommands(group: Command) -> list[tuple[str, Command]]:
    return [(name, command) for name, command in group.commands.items() if not command.hidden]


def _is_passthrough(command: Command) -> bool:
    return bool(command.context_settings.get("ignore_unknown_options"))


def _command_help(command: Command) -> str:
    return _cell(command.help or command.short_help)


def _leaf_section(path: str, command: Command) -> list[str]:
    lines = [f"## {path}", ""]
    help_text = _command_help(command)
    if help_text:
        lines += [help_text, ""]
    arguments, options = _split_params(command)
    if arguments:
        lines += ["**Arguments**", "", *_argument_table(arguments), ""]
    if options:
        lines += ["**Options**", "", *_option_table(options), ""]
    return lines


def _walk(path: str, command: Command) -> list[str]:
    if _is_group(command):
        lines = [f"## {path}", ""]
        help_text = _command_help(command)
        if help_text:
            lines += [help_text, ""]
        _, options = _split_params(command)
        if options:
            lines += ["**Options**", "", *_option_table(options), ""]
        for name, child in _subcommands(command):
            lines += _walk(f"{path} {name}", child)
        return lines
    return _leaf_section(path, command)


def _passthrough_list(entries: list[tuple[str, Command]]) -> list[str]:
    lines = ["## Provider passthrough", "", "Each entry forwards every remaining argument to that provider's own CLI.", ""]
    for name, command in entries:
        lines.append(f"- `warcraft {name} ...` -> [{name}]({name}.md): {_command_help(command)}")
    lines.append("")
    return lines


def render(script_name: str, group: Command) -> str:
    lines = [GENERATED_HEADER, "", f"# {script_name}", ""]
    help_text = _command_help(group)
    if help_text:
        lines += [help_text, ""]
    _, global_options = _split_params(group)
    if global_options:
        lines += [
            "## Global options",
            "",
            f"Pass these before the subcommand: `{script_name} --pretty <command> ...`.",
            "",
            *_option_table(global_options),
            "",
        ]
    if _is_group(group):
        passthrough: list[tuple[str, Command]] = []
        for name, command in _subcommands(group):
            if _is_passthrough(command):
                passthrough.append((name, command))
            else:
                lines += _walk(f"{script_name} {name}", command)
        if passthrough:
            lines += _passthrough_list(passthrough)
    return "\n".join(lines).rstrip() + "\n"


def render_index(scripts: dict[str, str]) -> str:
    from warcraft_cli.providers import list_providers

    tier_by_command = {registration.command: registration.tier for registration in list_providers()}
    description_by_command = {registration.command: registration.description for registration in list_providers()}
    lines = [
        GENERATED_HEADER,
        "",
        "# Command reference",
        "",
        "One file per console script, generated from the Typer apps. Flags, defaults, and help text",
        "live here only; `docs/USAGE.md` carries workflows and conventions.",
        "",
        "| Command | Tier | Reference | Notes |",
        "| --- | --- | --- | --- |",
    ]
    for name in scripts:
        tier = tier_by_command.get(name, "core")
        note = _cell(description_by_command.get(name, "Cross-provider wrapper and composite commands."))
        lines.append(f"| `{name}` | {tier} | [{name}.md]({name}.md) | {note} |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate(output_dir: Path) -> dict[Path, str]:
    scripts = console_scripts()
    rendered = {output_dir / f"{name}.md": render(name, _load_group(entry)) for name, entry in scripts.items()}
    rendered[output_dir / "README.md"] = render_index(scripts)
    return rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR, help="Directory to write the reference into.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero when the files on disk differ from the generated output.")
    args = parser.parse_args()

    output_dir: Path = args.output_dir
    rendered = generate(output_dir)

    if args.check:
        stale = [
            path
            for path, text in rendered.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if stale:
            for path in stale:
                print(f"stale: {path}", file=sys.stderr)
            print("Run `make reference`.", file=sys.stderr)
            return 1
        return 0

    output_dir.mkdir(parents=True, exist_ok=True)
    for path, text in rendered.items():
        path.write_text(text, encoding="utf-8")
        print(path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
