#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKTREE_META_DIR="$ROOT_DIR/.warcraft"
RUNTIME_ROOT="$WORKTREE_META_DIR/runtime"
ENV_PATH="$WORKTREE_META_DIR/worktree-env.sh"

mkdir -p "$WORKTREE_META_DIR"

cat > "$ENV_PATH" <<EOF
#!/usr/bin/env bash
# Generated by scripts/setup_worktree_env.sh
# This keeps branch-local runtime data and cache inside the worktree while
# leaving shared config/state in the host-level XDG roots for seamless auth reuse.

export WARCRAFT_WORKTREE_ROOT="$ROOT_DIR"
export WARCRAFT_WORKTREE_RUNTIME_DIR="$RUNTIME_ROOT"

case ":\${PATH:-}:" in
  *:"$ROOT_DIR/.venv/bin":*)
    ;;
  *)
    export PATH="$ROOT_DIR/.venv/bin:\$PATH"
    ;;
esac
EOF

chmod +x "$ENV_PATH"

echo "Wrote worktree env: $ENV_PATH"
echo "Source with: source \"$ENV_PATH\""
